version: '3'
services:
  python3:
    build:
      context: .
      dockerfile: 'git/Dockerfile'
    container_name: 'elegant-curve'
    tty: true
    restart: always
    volumes:
      - ./:/elegant-curve
    working_dir: '/elegant-curve'
